services:
  - type: web
    name: seat-allocation
    env: python
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.9"
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    plan: free
